services:
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - LABEL_STUDIO_HOST=http://localhost:8080
      - LABEL_STUDIO_STORAGE=/data
    restart: no

  ml-backend:
    build:
      context: ./label-studio-backend
    container_name: label-studio-ml-backend
    ports:
      - "9090:9090"
      - "5000:5000"
    volumes:
      - ./data:/data
      - python_libraries:/usr/local/lib/python3.9/site-packages
    restart: no
volumes:
  python_libraries:
