version: "3.8"

services:
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - LABEL_STUDIO_HOST=http://0.0.0.0:8080
      - LABEL_STUDIO_STORAGE=/data
    restart: always

  ml-backend:
    build:
      context: ./label-studio-backend
    container_name: label-studio-ml-backend
    ports:
      - "9090:9090"
    volumes:
      - ./data:/data
    restart: always
